// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRXy6zYE0sof5CLAR1GMJiHSU3Wq_xqzY',
    appId: '1:868216125774:web:7ce200e3b990089c52c61f',
    messagingSenderId: '868216125774',
    projectId: 'beastmode-8c659',
    authDomain: 'beastmode-8c659.firebaseapp.com',
    storageBucket: 'beastmode-8c659.firebasestorage.app',
    measurementId: 'G-KVBD114BRQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-F-gD9l3fuXt3QrnafxkHYicAcozgmBQ',
    appId: '1:868216125774:android:73e7e584a748065b52c61f',
    messagingSenderId: '868216125774',
    projectId: 'beastmode-8c659',
    storageBucket: 'beastmode-8c659.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBMNWWD11jlDBQrAl0xDk578P2yghRDvJo',
    appId: '1:868216125774:ios:4da950020a8e037d52c61f',
    messagingSenderId: '868216125774',
    projectId: 'beastmode-8c659',
    storageBucket: 'beastmode-8c659.firebasestorage.app',
    iosBundleId: 'com.example.beastMode',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBMNWWD11jlDBQrAl0xDk578P2yghRDvJo',
    appId: '1:868216125774:ios:4da950020a8e037d52c61f',
    messagingSenderId: '868216125774',
    projectId: 'beastmode-8c659',
    storageBucket: 'beastmode-8c659.firebasestorage.app',
    iosBundleId: 'com.example.beastMode',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBRXy6zYE0sof5CLAR1GMJiHSU3Wq_xqzY',
    appId: '1:868216125774:web:1bbf13e10b98567452c61f',
    messagingSenderId: '868216125774',
    projectId: 'beastmode-8c659',
    authDomain: 'beastmode-8c659.firebaseapp.com',
    storageBucket: 'beastmode-8c659.firebasestorage.app',
    measurementId: 'G-1DYCN7TGDN',
  );
}
